---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.8

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible==$ANSIBLE_VERSION

before_script:
  - cd tests

script:
  - "ansible-playbook ./playbook.yml --syntax-check"
  - "ansible-playbook ./playbook.yml --connection=local --sudo"
  - >
    ansible-playbook ./playbook.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/92047b32b13603807c99
    on_success: change
    on_failure: always
    on_start: false
