- name: Ensure configuration is correct
  notify: Restart NTP
  template:
    src: ntp.conf.j2
    dest: "/etc/ntp.conf"
    mode: 0644
  when: ansible_os_family == "Debian"
  tags:
    - geekchimp
    - debian
    - ntp
    - configuration

- name: Ensure DHCP created NTP configuration is non-existing
  notify: Restart NTP
  file:
    path: "/var/lib/ntp/ntp.conf.dhcp"
    state: absent
  when: ansible_os_family == "Debian" and ntp_remove_dhcp_configuration
  tags:
    - geekchimp
    - debian
    - ntp
    - configuration

- name: Ensure NTP is running and enabled at system start
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_os_family == "Debian and ntp_enabled
  tags:
    - geekchimp
    - debian
    - ntp
    - configuration

- name: Ensure NTP is stopped and disabled at system start
  service:
    name: ntp
    state: stopped
    enabled: no
  when: ansible_os_family == "Debian and not ntp_enabled
  tags:
    - geekchimp
    - debian
    - ntp
    - configuration
