---
- name: Ensure NTP is installed
  apt:
    name: ntp
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - geekchimp
    - debian
    - ntp
    - installation
